##############################
###### GENERAL SETTINGS ######
##############################
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import:
      - optional:file:.env[.properties]
      - application-database-dev.yaml
  web:
    error:
      include-message: always
      path: ${SPRING_WEB_ERROR_PATH}

